services:
  postgres:
    container_name: postgres
    build: containers/postgres
    volumes:
      - ./containers/postgres/volume/data:/app
      - ./containers/postgres/volume/data/postgres:/var/lib/postgresql/data
    networks:
      - postgres
    ports:
      - 5432:5432

  adminer:
    container_name: adminer_postgres
    image: adminer:4.8.1-standalone
    networks:
        - postgres 

  haproxy:
    container_name: haproxy_postgres
    build: containers/haproxy
    volumes:
      - ./containers/haproxy/volume:/app 
    networks:
      - postgres
    ports:
      - 8081:8080

networks:
  postgres:
    name: postgres 
    external: true
